spring:
  application:
    name: schedule-sharing-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:schedule_sharing_service}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
#          show_sql: true
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration, classpath:db/data

logging.level.org:
  springframework: info
  hibernate:
    SQL: debug
    orm.jdbc.bind: trace