name: Test
on:
  pull_request:
    paths:
      - '**/*.java'
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.31
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run tests
        run: chmod +x gradlew && ./gradlew test --no-daemon
        env:
          DB_USERNAME: root
          DB_PASSWORD: root